# Define goal message
int32 input
float32 x
float32 y
float32 theta
---
# Define the result (done) message
int32 output
int32 goal_stamp
---
# Define feedback message
int32 fdbk
float32 x
float32 y
float32 theta
