# Define goal message
int32 input
float32 x1
float32 y1
float32 theta1
float32 x2
float32 y2
float32 theta2
---
# Define the result (done) message
int32 result
---
# Define feedback message
bool is_spinning
